/*
 * data_loader.h — runtime loading of bulk asset blobs.
 *
 * The walker visual asset blobs (font glyphs, course bitmaps, Pokemon
 * sprites, item icons) are NOT bundled with pkwbridge. They are loaded
 * at boot from SD:
 *
 *   sdmc:/3ds/pokeStride/data/font_sys_glyphs.bin
 *   sdmc:/3ds/pokeStride/data/font_sys_widths.bin
 *   sdmc:/3ds/pokeStride/data/course_bitmaps.bin
 *   sdmc:/3ds/pokeStride/data/phcgra_data.bin
 *   sdmc:/3ds/pokeStride/data/phcicon_data.bin
 *
 * Each file is generated by an extractor script from the user's own
 * pwflash.rom + SoulSilver.nds. If any file is missing,
 * the corresponding `loaded` flag stays false and the call sites that
 * write visual content to the walker skip those writes — the walker
 * keeps whatever the template pweep already had.
 */
#ifndef DATA_LOADER_H
#define DATA_LOADER_H

#include <stdbool.h>

/* Call once at app boot, after applog_open. Tries each .bin under
 * sdmc:/3ds/pokeStride/data/. Logs each attempt. */
void app_data_init(void);

/* Per-blob status accessors. False if the file was missing or short. */
bool app_data_font_loaded(void);
bool app_data_course_bitmaps_loaded(void);
bool app_data_phcgra_loaded(void);
bool app_data_phcicon_loaded(void);

#endif
