/* personal_gen4.c - runtime personal-data tables.
 *
 * The per-species gender ratio + growth rate are NOT baked in. They are
 * loaded at boot from sdmc:/3ds/pokeStride/data/personal.bin, generated by
 * nds_extract.c::extract_personal from the user's own HGSS cartridge.
 * See personal_gen4.h for the rationale and format.
 *
 * personal.bin format: [4B "PRS1"][N gender bytes][N growth bytes]
 * with N = PERSONAL_GEN4_COUNT.
 */
#include "personal_gen4.h"

#include <stdio.h>
#include <string.h>

/* Neutral defaults until the cache loads: 50% gender ratio (0x7F),
 * Medium-Fast growth (0). Means "send"/"claim" never crash on a fresh
 * install; they just may pick a wrong gender/EXP until the user runs the
 * one-time NDS extraction (which every other asset already requires). */
uint8_t personal_gen4_gender_ratio[PERSONAL_GEN4_COUNT];
uint8_t personal_gen4_growth_rate [PERSONAL_GEN4_COUNT];

static bool g_loaded = false;

#define PERSONAL_BIN_PATH  "sdmc:/3ds/pokeStride/data/personal.bin"

static void set_defaults(void) {
    for (int i = 0; i < PERSONAL_GEN4_COUNT; i++) {
        personal_gen4_gender_ratio[i] = 0x7F;
        personal_gen4_growth_rate[i]  = 0x00;
    }
}

bool personal_loaded(void) { return g_loaded; }

bool personal_init(void) {
    /* Always start from neutral defaults so a failed/partial load can't
     * leave stale or garbage values. */
    set_defaults();
    g_loaded = false;

    FILE *f = fopen(PERSONAL_BIN_PATH, "rb");
    if (!f) return false;

    uint8_t magic[4];
    if (fread(magic, 1, 4, f) != 4 ||
        magic[0] != 'P' || magic[1] != 'R' ||
        magic[2] != 'S' || magic[3] != '1') {
        fclose(f);
        return false;
    }

    uint8_t gender[PERSONAL_GEN4_COUNT];
    uint8_t growth[PERSONAL_GEN4_COUNT];
    if (fread(gender, 1, PERSONAL_GEN4_COUNT, f) != PERSONAL_GEN4_COUNT ||
        fread(growth, 1, PERSONAL_GEN4_COUNT, f) != PERSONAL_GEN4_COUNT) {
        fclose(f);
        return false;
    }
    fclose(f);

    /* Sanity anchor (region-independent fact): Bulbasaur = 12.5% female
     * = 0x1F. Guards against a corrupt or mis-extracted cache. */
    if (gender[1] != 0x1F) return false;

    memcpy(personal_gen4_gender_ratio, gender, PERSONAL_GEN4_COUNT);
    memcpy(personal_gen4_growth_rate,  growth, PERSONAL_GEN4_COUNT);
    g_loaded = true;
    return true;
}
