/* phcgra_data.c — runtime-loaded Pokemon big-sprite archive.
 *
 * BSS storage for the 664 × 1536 B sprite entries. Filled by
 * data_loader.c at boot from
 *   sdmc:/3ds/pokeStride/data/phcgra_data.bin
 * (generated by scripts/extract_nds.py from the user's HGSS NDS dump).
 *
 * phcgra_index_from_species lives in phcgra_index.c (small lookup
 * table, kept compiled-in — it's just an integer index map).
 */
#include "phcgra_data.h"

uint8_t phcgra_data[PHCGRA_COUNT][PHCGRA_ENTRY_SIZE];

const uint8_t *phcgra_get(uint16_t archive_index) {
    if (archive_index >= PHCGRA_COUNT) return 0;
    return phcgra_data[archive_index];
}
